# fly.toml app configuration file generated for 09-complete-server on 2025-09-01T18:03:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '09-complete-server-2'
primary_region = 'cdg'

[build.args]
NODE_VERSION = "20"

[env]
PORT = '8080'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = off
  auto_start_machines = true
  min_machines_running = 1
  
  [[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
